// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyONfiGVP1gWpVmOJQpY_nf9ysR5-CZL0',
    appId: '1:660938414572:web:f2f5f2f38203909f1848c9',
    messagingSenderId: '660938414572',
    projectId: 'flutter-all-in-one-project',
    authDomain: 'flutter-all-in-one-project.firebaseapp.com',
    storageBucket: 'flutter-all-in-one-project.firebasestorage.app',
    measurementId: 'G-GDE71W21R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfpohMGaf6eyhG-Q1vze_JAjUOdcyJ6A0',
    appId: '1:660938414572:android:4eb33ac0c12c2bbb1848c9',
    messagingSenderId: '660938414572',
    projectId: 'flutter-all-in-one-project',
    storageBucket: 'flutter-all-in-one-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVzibWHdmEQJkQ6MxucPBrznVcbtjWatY',
    appId: '1:660938414572:ios:6f2ae5c8cc25aa581848c9',
    messagingSenderId: '660938414572',
    projectId: 'flutter-all-in-one-project',
    storageBucket: 'flutter-all-in-one-project.firebasestorage.app',
    androidClientId: '660938414572-6ivaargsoepp7f42fpdqh6tdlpqs955h.apps.googleusercontent.com',
    iosClientId: '660938414572-ovlcr4js38lqui3ac5u528jeik1nabql.apps.googleusercontent.com',
    iosBundleId: 'com.example.alInOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVzibWHdmEQJkQ6MxucPBrznVcbtjWatY',
    appId: '1:660938414572:ios:6f2ae5c8cc25aa581848c9',
    messagingSenderId: '660938414572',
    projectId: 'flutter-all-in-one-project',
    storageBucket: 'flutter-all-in-one-project.firebasestorage.app',
    androidClientId: '660938414572-6ivaargsoepp7f42fpdqh6tdlpqs955h.apps.googleusercontent.com',
    iosClientId: '660938414572-ovlcr4js38lqui3ac5u528jeik1nabql.apps.googleusercontent.com',
    iosBundleId: 'com.example.alInOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyONfiGVP1gWpVmOJQpY_nf9ysR5-CZL0',
    appId: '1:660938414572:web:93707de1c2f3313e1848c9',
    messagingSenderId: '660938414572',
    projectId: 'flutter-all-in-one-project',
    authDomain: 'flutter-all-in-one-project.firebaseapp.com',
    storageBucket: 'flutter-all-in-one-project.firebasestorage.app',
    measurementId: 'G-RS0R6XL9BE',
  );

}